/* Eleventy config. Replaces bin/build, which assembled one page out of sixteen.
 *
 *   npx eleventy              build to _site/
 *   npx eleventy --serve      dev server with live reload
 *   ELEVENTY_ENV=production npx eleventy    strip dev comments
 *
 * Three things Eleventy does not do are kept here, because losing any of them
 * is silent rather than loud:
 *
 *   1. styles/home.entry.css is generated from a glob of parts/*.css, because
 *      Lightning CSS --bundle takes no glob and @import takes no glob either.
 *      Without it a new band sheet is simply never imported and nobody is told.
 *   2. Lightning CSS runs with --minify AND --targets. The targets are a bug
 *      fix, not tuning; the reasoning is at the call site below.
 *   3. --prod comment stripping, now a transform.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(ROOT, "_site");
const PROD = process.env.ELEVENTY_ENV === "production";

/* home.entry.css lists the band sheets, because @import takes no glob.
 *
 * Generated, so adding parts/<band>.css is the only step. Nobody has to
 * remember to register it, which is the kind of bookkeeping that rots.
 *
 * The two homepage sheets above the bands are named rather than globbed: the
 * layer each one lands in is a decision, not a filename convention, and
 * styles/ also holds the entry files themselves and the shared sheet. */
function writeHomeEntry() {
  const bands = readdirSync(resolve(ROOT, "parts"))
    .filter((f) => f.endsWith(".css"))
    .map((f) => f.replace(/\.css$/, ""))
    .sort();
  writeFileSync(resolve(ROOT, "styles/home.entry.css"),
    "/* Entry for home.css. GENERATED by eleventy.config.js: the band list comes\n" +
    "   from parts/*.css, because @import takes no glob. Edit a band's own sheet,\n" +
    "   or add a new parts/<band>.css and rebuild. */\n\n" +
    "@layer tokens, base, components, bands;\n\n" +
    '@import "primitives.css" layer(base);\n' +
    '@import "grammar.css" layer(components);\n' +
    bands.map((b) => `@import "../parts/${b}.css" layer(bands);\n`).join(""),
    "utf8");
}

/* Flatten an entry's @imports into one sheet with Lightning CSS.
 *
 * A real bundler rather than string concatenation. It parses, so it cannot cut
 * a multi-line selector list in half the way a line filter can, and it
 * understands @layer, so the cascade is declared in the entry files instead of
 * being implied by the order a script pasted things together in. */
function bundle(entry, out) {
  // --minify is safe to run always: both linters read styles/ and parts/, never
  // the generated sheets, so compressed representations (rgba(0,122,255,.1) ->
  // #007aff1a) never reach the curb's hex detector.
  //
  // --targets is not optional here, it is a bug fix. With no targets set,
  // Lightning CSS rewrites every breakpoint into Media Queries Level 4 range
  // syntax that nobody wrote: `@media (width<=899px)` in place of max-width.
  // That is Safari 16.4+, and on anything older the query does not parse, so
  // the whole responsive layout silently stops applying on a site whose
  // audience is macOS. 28 of them were shipping. Targets lower all 28 back for
  // 341 bytes.
  //
  // safari 15 is the floor because it is what the range syntax costs us;
  // nothing else in the sheet downlevels at that target. color-mix() taking
  // var() cannot resolve statically and is left alone, @layer is untouched,
  // and corner-shape:squircle survives as the progressive enhancement it is.
  // Verify with scripts/cssdiff.mjs if you move it.
  execFileSync(resolve(ROOT, "node_modules/.bin/lightningcss"),
    ["--bundle", "--minify", "--targets", "safari >= 15, chrome >= 100, firefox >= 100",
      `styles/${entry}`, "-o", out],
    { cwd: ROOT, stdio: ["ignore", "inherit", "inherit"] });
}

/* Drop HTML comments for production.
 *
 * 17% of index.html is comments, and they are design rationale written for
 * whoever edits parts/ next: they cite app source files, name commits, and
 * explain decisions. That is exactly the material to keep in the repo and not
 * ship to strangers. Conditional comments are spared, though this site has
 * none. */
const COMMENT = /[ \t]*<!--(?!\[if)[\s\S]*?-->[ \t]*\n?/g;
const stripDev = (html) => html.replace(COMMENT, "").replace(/\n{3,}/g, "\n\n");

export default function (eleventyConfig) {
  eleventyConfig.addPassthroughCopy("assets");
  eleventyConfig.addPassthroughCopy("screenshots");
  eleventyConfig.addPassthroughCopy("home.js");
  eleventyConfig.addPassthroughCopy("apple-touch-icon.png");
  eleventyConfig.addPassthroughCopy("icon.png");
  eleventyConfig.addPassthroughCopy("CNAME");
  eleventyConfig.addPassthroughCopy("robots.txt");
  eleventyConfig.addPassthroughCopy("llms.txt");
  eleventyConfig.addPassthroughCopy("sitemap.xml");
  eleventyConfig.addPassthroughCopy("appcast.xml");

  // parts/ is watched for free because it is dir.includes; styles/ is not, so
  // under --serve a save to tokens.css did nothing at all and read as a stale
  // cache. That is the file CLAUDE.md sends you to for any colour, surface,
  // radius, shadow or measure, i.e. the most-edited sheet in the repo.
  eleventyConfig.addWatchTarget("styles/");

  /* URLs on this site end in .html and always have: sitemap.xml, every internal
     link and nginx's try_files all assume it. Eleventy's default would publish
     features.html to /features/index.html and quietly break every one of them.
     Derived from the filename so a new page needs no front matter to land in
     the right place; index.src.html is the homepage's source, hence the .src. */
  eleventyConfig.addGlobalData("eleventyComputed", {
    permalink: (data) => `${data.page.filePathStem.replace(/\.src$/, "")}.html`,
    /* "features", "index", ... The nav and footer compare against this rather
       than carrying a hand-set aria-current, which had drifted: 4 of 12 pages
       marked their nav link and 3 marked their footer link. */
    pageName: (data) => data.page.filePathStem.replace(/\.src$/, "").replace(/^\//, ""),
    home: (data) => data.page.filePathStem === "/index.src",
    canonical: (data) => data.page.filePathStem === "/index.src"
      ? "https://steer.seanfloyd.dev/"
      : `https://steer.seanfloyd.dev${data.page.filePathStem}.html`,
  });

  /* Footer defaults. A page overrides only what differs from every other page. */
  eleventyConfig.addGlobalData("footBottom", true);
  eleventyConfig.addGlobalData("footLegal",
    "macOS 14+ · Apple Silicon · Not affiliated with Sony, Microsoft, or Nintendo.");

  eleventyConfig.addTransform("strip-dev-comments", function (content) {
    if (!PROD || !this.page.outputPath?.endsWith(".html")) return content;
    return stripDev(content);
  });

  eleventyConfig.on("eleventy.before", writeHomeEntry);
  eleventyConfig.on("eleventy.after", () => {
    mkdirSync(OUT, { recursive: true });
    bundle("site.entry.css", "_site/styles.css");
    bundle("home.entry.css", "_site/home.css");
  });

  return {
    dir: {
      input: ".",
      output: "_site",
      /* parts/, not _includes/. parts/<band>.html sits beside parts/<band>.css
         on purpose: it is what lets a delegated agent be handed exactly two
         files and nothing else. */
      includes: "parts",
      layouts: "parts",
      data: "_data",
    },
    htmlTemplateEngine: "njk",
    markdownTemplateEngine: "njk",
  };
}
