/* Eleventy config. Replaces bin/build, which assembled one page out of sixteen.
 *
 *   npx eleventy              build to dist/
 *   npx eleventy --serve      dev server with live reload
 *
 * Three things Eleventy does not do are kept here, because losing any of them
 * is silent rather than loud:
 *
 *   1. styles/home.entry.css is generated from a glob of styles/bands/*.css,
 *      because Lightning CSS --bundle takes no glob and @import takes no glob
 *      either. Without it a new band sheet is simply never imported and nobody
 *      is told.
 *   2. Lightning CSS runs with --minify AND --targets. The targets are a bug
 *      fix, not tuning; the reasoning is at the call site below.
 *   3. --prod comment stripping, now a transform.
 */
import { execFileSync } from "node:child_process";
import { minify } from "html-minifier-next";
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(ROOT, "dist");

/* home.entry.css lists the band sheets, because @import takes no glob.
 *
 * Generated, so adding styles/bands/<band>.css is the only step. Nobody has to
 * remember to register it, which is the kind of bookkeeping that rots.
 *
 * The two homepage sheets above the bands are named rather than globbed: the
 * layer each one lands in is a decision, not a filename convention, and
 * styles/ also holds the entry files themselves and the shared sheet. */
function writeHomeEntry() {
  const bands = readdirSync(resolve(ROOT, "styles/bands"))
    .filter((f) => f.endsWith(".css"))
    .map((f) => f.replace(/\.css$/, ""))
    .sort();
  writeFileSync(resolve(ROOT, "styles/home.entry.css"),
    "/* Entry for home.css. GENERATED by eleventy.config.js: the band list comes\n" +
    "   from styles/bands/*.css, because @import takes no glob. Edit a band's own\n" +
    "   sheet, or add a new styles/bands/<band>.css and rebuild. */\n\n" +
    "@layer tokens, base, components, bands;\n\n" +
    '@import "svg-strokes.css" layer(base);\n' +
    '@import "design-system.css" layer(components);\n' +
    bands.map((b) => `@import "bands/${b}.css" layer(bands);\n`).join(""),
    "utf8");
}

/* A page's sheet is at the same path in the other tree, exactly like a band's.
 *
 * Swap the directory and the extension: vs.html is styled by
 * styles/pages/vs.css, which is bundled to dist/vs.css and linked by the
 * layout for that page and no other. Derivable by rule, so there is no map to
 * go stale and no front matter to remember.
 *
 * This exists so styles/shared.css can stay shared. It ships on all 14 pages,
 * and it was carrying rules one page used, while five pages carried a <style>
 * block in their front matter instead. Both are the same mistake in opposite
 * directions.
 *
 * Page sheets are UNLAYERED on purpose. They replace <style> blocks that sat in
 * <head> after the site.css link, i.e. unlayered, which outranks every layer in
 * site.css whatever the specificity. Putting them in a layer would quietly hand
 * some of those rules back to shared.css. Nothing else on the site is unlayered:
 * site.entry.css and home.entry.css import every sheet into a layer. */
const pageSheets = () => (existsSync(resolve(ROOT, "styles/pages"))
  ? readdirSync(resolve(ROOT, "styles/pages"))
    .filter((f) => f.endsWith(".css")).map((f) => f.replace(/\.css$/, "")).sort()
  : []);

/* Flatten an entry's @imports into one sheet with Lightning CSS.
 *
 * A real bundler rather than string concatenation. It parses, so it cannot cut
 * a multi-line selector list in half the way a line filter can, and it
 * understands @layer, so the cascade is declared in the entry files instead of
 * being implied by the order a script pasted things together in. */
/* theme.ts is the only source the browser gets that is not shippable as-is, so
   it is compiled here rather than passed through. Its own tsconfig, because the
   root one is a CHECKER (noEmit, and it covers the Node tools too) and this is a
   BUILD: different target, different lib, and it must actually write a file.
   Fails the build loudly -- execFileSync throws on a non-zero exit -- since a
   silently missing theme.js leaves fourteen pages with a dead control. */
/* JS was the one language the production build did not touch: Lightning CSS
   minifies the sheets and the markup is minified too, while
   home.js and theme.js shipped 6.2KB of comments to every visitor. */
function minifyJs() {
  execFileSync(resolve(ROOT, "node_modules/.bin/esbuild"),
    [resolve(OUT, "home.js"), resolve(OUT, "theme.js"), "--minify", `--outdir=${OUT}`, "--allow-overwrite"],
    { stdio: "inherit" });
}

function compileBrowserTs() {
  execFileSync(resolve(ROOT, "node_modules/.bin/tsc"),
    ["-p", resolve(ROOT, "tsconfig.browser.json")], { stdio: "inherit" });
}

function bundle(entry, out) {
  // --minify is safe to run always: both linters read the hand-written sheets
  // under styles/, never the generated ones, so compressed representations
  // (rgba(0,122,255,.1) ->
  // #007aff1a) never reach the curb's hex detector.
  //
  // --targets is not optional here, it is a bug fix. With no targets set,
  // Lightning CSS rewrites every breakpoint into Media Queries Level 4 range
  // syntax that nobody wrote: `@media (width<=899px)` in place of max-width.
  // That is Safari 16.4+, and on anything older the query does not parse, so
  // the whole responsive layout silently stops applying on a site whose
  // audience is macOS. 28 of them were shipping. Targets lower all 28 back for
  // 341 bytes.
  //
  // safari 15 is the floor because it is what the range syntax costs us;
  // nothing else in the sheet downlevels at that target. color-mix() taking
  // var() cannot resolve statically and is left alone, @layer is untouched,
  // and corner-shape:squircle survives as the progressive enhancement it is.
  // Verify with scripts/cssdiff.mjs if you move it.
  execFileSync(resolve(ROOT, "node_modules/.bin/lightningcss"),
    ["--bundle", "--minify", "--targets", "safari >= 15, chrome >= 100, firefox >= 100",
      `styles/${entry}`, "-o", out],
    { cwd: ROOT, stdio: ["ignore", "inherit", "inherit"] });
}

/* Drop HTML comments for production.
 *
 * 17% of index.html is comments, and they are design rationale written for
 * whoever edits _includes/ next: they cite app source files, name commits, and
 * explain decisions. That is exactly the material to keep in the repo and not
 * ship to strangers. */
/* conservativeCollapse never removes whitespace, only collapses runs to one
   space: this page leans on inline-block rows where a removed space closes a
   gap the design wants. minifyJS reaches the pre-paint <head> script, the one
   file no other minifier can see because Nunjucks pastes it verbatim. */
const MINIFY = {
  removeComments: true,
  collapseWhitespace: true,
  conservativeCollapse: true,
  minifyJS: true,
  keepClosingSlash: true,
  /* Without this the minifier EXPANDS bare booleans to defer=defer and
     checked=checked -- unquoted, which html-validate rejects, and longer than
     what it replaced. */
  collapseBooleanAttributes: true,
  removeAttributeQuotes: false,
};

export default function (eleventyConfig) {
  /* Inline SVG lives in _includes/art/, not in the band markup, and is pasted
   * back by Nunjucks' own include:
   *
   *   {% include "art/hero-pad-ps.svg" %}
   *
   * hero.html was 46KB, 39KB of it pad geometry, so an agent sent to change one
   * line of copy read 46KB to find it. It is 7KB now. The output is unchanged
   * on purpose: this is a source-readability move, not a page-weight one.
   *
   * NO PLUGIN. eleventy-plugin-svg-contents does this and is in Eleventy's
   * community list, so it was adopted first — then measured. It last published
   * in 2022, pulls 31 packages for cheerio, and round-trips the file through a
   * parse and re-serialize instead of pasting bytes, which silently rewrapped a
   * <path> in three of the pad files. `{% include %}` is byte-identical to it,
   * ships with the template engine, and cannot reformat anything. Verified by
   * building both ways and diffing the output.
   *
   * WHY _includes/ AND NOT assets/svg/. These files are never served; the build
   * pastes them into the page. assets/svg/ holds pad-art-{mf,ps,sw,xb}.svg,
   * which ARE served and are fetched at runtime by home.js rewriting
   * use.padart's href. One directory holding both is how the next person
   * deletes the wrong one. _includes/ already means "things the build
   * assembles", which is exactly what these are.
   *
   * NAMED <band>-<thing>.svg, like everything else here: a band's files are
   * derivable from its name, so a delegated agent can be handed them without a
   * map. capabilities-face-cross.svg and hero-face-cross.svg are byte-identical
   * and stay separate for that reason.
   *
   * Nunjucks renders what it includes, so an SVG containing {{ or {% would be
   * interpreted. None does, and none should: these are art files. _includes/scripts/*.js is pasted the same way and is NOT art -- `{{` is plausible in JavaScript, and while a malformed one fails the build loudly, a well-formed `{{ name }}` renders to empty string and deletes code silently. */

  eleventyConfig.addPassthroughCopy("assets");
  eleventyConfig.addPassthroughCopy("screenshots");
  eleventyConfig.addPassthroughCopy("home.js");
  eleventyConfig.addPassthroughCopy("apple-touch-icon.png");
  eleventyConfig.addPassthroughCopy("icon.png");
  eleventyConfig.addPassthroughCopy("CNAME");
  eleventyConfig.addPassthroughCopy("robots.txt");
  eleventyConfig.addPassthroughCopy("llms.txt");
  eleventyConfig.addPassthroughCopy("sitemap.xml");
  eleventyConfig.addPassthroughCopy("appcast.xml");

  // _includes/ is watched for free because it is dir.includes; styles/ is not, so
  // under --serve a save to tokens.css did nothing at all and read as a stale
  // cache. That is the file CLAUDE.md sends you to for any colour, surface,
  // radius, shadow or measure, i.e. the most-edited sheet in the repo.
  eleventyConfig.addWatchTarget("styles/");

  /* URLs on this site end in .html and always have: sitemap.xml, every internal
     link and nginx's try_files all assume it. Eleventy's default would publish
     features.html to /features/index.html and quietly break every one of them.
     Derived from the filename so a new page needs no front matter to land in
     the right place; index.src.html is the homepage's source, hence the .src. */
  eleventyConfig.addGlobalData("eleventyComputed", {
    permalink: (data) => `${data.page.filePathStem.replace(/\.src$/, "")}.html`,
    /* "features", "index", ... The nav and footer compare against this rather
       than carrying a hand-set aria-current, which had drifted: 4 of 12 pages
       marked their nav link and 3 marked their footer link. */
    pageName: (data) => data.page.filePathStem.replace(/\.src$/, "").replace(/^\//, ""),
    home: (data) => data.page.filePathStem === "/index.src",
    canonical: (data) => data.page.filePathStem === "/index.src"
      ? "https://steer.seanfloyd.dev/"
      : `https://steer.seanfloyd.dev${data.page.filePathStem}.html`,
  });

  /* Footer defaults. A page overrides only what differs from every other page. */
  eleventyConfig.addGlobalData("footBottom", true);
  eleventyConfig.addGlobalData("footLegal",
    "macOS 14+ · Apple Silicon · Not affiliated with Sony, Microsoft, or Nintendo.");

  eleventyConfig.addTransform("minify-html", /** @this {{page?: {outputPath?: string}}} */ async function (content) {
    if (!this.page?.outputPath?.endsWith(".html")) return content;
    return minify(content, MINIFY);
  });

  /* The layout links <page>.css only for a page that has one, so a page with no
     sheet requests nothing. Read once at config time, like the band glob. */
  eleventyConfig.addGlobalData("pageSheets", pageSheets());

  eleventyConfig.on("eleventy.before", writeHomeEntry);
  eleventyConfig.on("eleventy.after", () => {
    mkdirSync(OUT, { recursive: true });
    bundle("site.entry.css", "dist/site.css");
    bundle("home.entry.css", "dist/home.css");
    for (const p of pageSheets()) bundle(`pages/${p}.css`, `dist/${p}.css`);
    compileBrowserTs();
    minifyJs();
  });

  return {
    dir: {
      input: ".",
      output: "dist",
      /* _includes/{bands,chrome,layouts}, mirrored by styles/{bands}. A band's
         two files are at the same path in each tree: swap _includes -> styles
         and .html -> .css and you have the sheet. Derivable by rule, so a
         delegated agent can still be handed exactly two files without anyone
         maintaining a map of where a band's CSS lives — and maps go stale. */
      includes: "_includes",
      layouts: "_includes",
      data: "_data",
    },
    htmlTemplateEngine: "njk",
    markdownTemplateEngine: "njk",
  };
}
