/* Eleventy config.
 *
 * Three things Eleventy does not do are done here because losing any of them
 * is silent rather than loud: the home.entry.css glob, Lightning CSS targets,
 * and comment stripping. Each is explained at its own call site. */
import { execFileSync } from "node:child_process";
import { minify } from "html-minifier-next";
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(ROOT, "dist");

/* Generated because @import takes no glob, so adding styles/bands/<band>.css is
   the only step. The two sheets above the bands are named rather than globbed:
   the layer each lands in is a decision, not a filename convention. */
function writeHomeEntry() {
  const bands = readdirSync(resolve(ROOT, "styles/bands"))
    .filter((f) => f.endsWith(".css"))
    .map((f) => f.replace(/\.css$/, ""))
    .sort();
  writeFileSync(resolve(ROOT, "styles/home.entry.css"),
    "/* Entry for home.css. GENERATED by eleventy.config.js: the band list comes\n" +
    "   from styles/bands/*.css, because @import takes no glob. Edit a band's own\n" +
    "   sheet, or add a new styles/bands/<band>.css and rebuild. */\n\n" +
    "@layer tokens, base, components, bands;\n\n" +
    '@import "svg-strokes.css" layer(base);\n' +
    '@import "design-system.css" layer(components);\n' +
    bands.map((b) => `@import "bands/${b}.css" layer(bands);\n`).join(""),
    "utf8");
}

/* A page's sheet is at the same path in the other tree, like a band's: swap the
   directory and the extension and vs.html gives styles/pages/vs.css.
   UNLAYERED on purpose. These replace <style> blocks that sat after the
   site.css link, which outranks every layer in it whatever the specificity;
   putting them in a layer hands those rules back to shared.css. Nothing else
   on the site is unlayered. */
const pageSheets = () => (existsSync(resolve(ROOT, "styles/pages"))
  ? readdirSync(resolve(ROOT, "styles/pages"))
    .filter((f) => f.endsWith(".css")).map((f) => f.replace(/\.css$/, "")).sort()
  : []);

/* Flatten an entry's @imports into one sheet with Lightning CSS.
 *
 * A real bundler rather than string concatenation. It parses, so it cannot cut
 * a multi-line selector list in half the way a line filter can, and it
 * understands @layer, so the cascade is declared in the entry files instead of
 * being implied by the order a script pasted things together in. */
/* theme.ts is the only source the browser gets that is not shippable as-is, so
   it is compiled here rather than passed through. Its own tsconfig, because the
   root one is a CHECKER (noEmit, and it covers the Node tools too) and this is a
   BUILD: different target, different lib, and it must actually write a file.
   Fails the build loudly -- execFileSync throws on a non-zero exit -- since a
   silently missing theme.js leaves fourteen pages with a dead control. */
/* JS was the one language the production build did not touch: Lightning CSS
   minifies the sheets and the markup is minified too, while
   home.js and theme.js shipped 6.2KB of comments to every visitor. */
function minifyJs() {
  execFileSync(resolve(ROOT, "node_modules/.bin/esbuild"),
    [resolve(OUT, "home.js"), resolve(OUT, "theme.js"), "--minify", `--outdir=${OUT}`, "--allow-overwrite"],
    { stdio: "inherit" });
}

function compileBrowserTs() {
  execFileSync(resolve(ROOT, "node_modules/.bin/tsc"),
    ["-p", resolve(ROOT, "tsconfig.browser.json")], { stdio: "inherit" });
}

function bundle(entry, out) {
  // --targets is a bug fix, not tuning. Unset, Lightning CSS rewrites every
  // breakpoint into Media Queries Level 4 range syntax (`@media (width<=899px)`)
  // which is Safari 16.4+, so on anything older the whole responsive layout
  // silently stops applying. safari 15 is the floor because that is what the
  // range syntax costs; nothing else in the sheet downlevels there.
  // Diff the computed styles before and after if you move it.
  execFileSync(resolve(ROOT, "node_modules/.bin/lightningcss"),
    ["--bundle", "--minify", "--targets", "safari >= 15, chrome >= 100, firefox >= 100",
      `styles/${entry}`, "-o", out],
    { cwd: ROOT, stdio: ["ignore", "inherit", "inherit"] });
}

/* Drop HTML comments for production.
 *
 * 17% of index.html is comments, and they are design rationale written for
 * whoever edits _includes/ next: they cite app source files, name commits, and
 * explain decisions. That is exactly the material to keep in the repo and not
 * ship to strangers. */
/* conservativeCollapse never removes whitespace, only collapses runs to one
   space: this page leans on inline-block rows where a removed space closes a
   gap the design wants. minifyJS reaches the pre-paint <head> script, the one
   file no other minifier can see because Nunjucks pastes it verbatim. */
const MINIFY = {
  removeComments: true,
  collapseWhitespace: true,
  conservativeCollapse: true,
  minifyJS: true,
  keepClosingSlash: true,
  /* Without this the minifier EXPANDS bare booleans to defer=defer and
     checked=checked -- unquoted, which html-validate rejects, and longer than
     what it replaced. */
  collapseBooleanAttributes: true,
  removeAttributeQuotes: false,
};

export default function (eleventyConfig) {
  /* NO PLUGIN for the inline SVG in src/_includes/art/: eleventy-plugin-svg-
     contents was adopted first, then measured. It last published in 2022, pulls
     31 packages for cheerio, and re-serializes instead of pasting bytes, which
     rewrapped a <path> in three pad files. `{% include %}` is byte-identical.
     Nunjucks renders what it includes, so a well-formed `{{ name }}` in one of
     these files renders to empty string and deletes code silently. */

  /* src/public/ lands at the output root, so a file that has to ship under its
     own name is added by putting it there, not by editing this list. The list
     it replaces named ten files, and a root asset that was not on it -- probed
     with probe-asset.png -- was dropped without a word. */
  eleventyConfig.addPassthroughCopy("src/assets");
  eleventyConfig.addPassthroughCopy("src/screenshots");
  eleventyConfig.addPassthroughCopy("src/home.js");
  eleventyConfig.addPassthroughCopy({ "src/public": "/" });

  // _includes/ is watched for free because it is dir.includes; styles/ is not, so
  // under --serve a save to tokens.css did nothing at all and read as a stale
  // cache. That is the file CLAUDE.md sends you to for any colour, surface,
  // radius, shadow or measure, i.e. the most-edited sheet in the repo.
  eleventyConfig.addWatchTarget("styles/");

  /* URLs on this site end in .html and always have: sitemap.xml, every internal
     link and nginx's try_files all assume it. Eleventy's default would publish
     features.html to /features/index.html and quietly break every one of them.
     Derived from the filename so a new page needs no front matter to land in
     the right place; index.src.html is the homepage's source, hence the .src. */
  eleventyConfig.addGlobalData("eleventyComputed", {
    permalink: (data) => `${data.page.filePathStem.replace(/\.src$/, "")}.html`,
    /* "features", "index", ... The nav and footer compare against this rather
       than carrying a hand-set aria-current, which had drifted: 4 of 12 pages
       marked their nav link and 3 marked their footer link. */
    pageName: (data) => data.page.filePathStem.replace(/\.src$/, "").replace(/^\//, ""),
    home: (data) => data.page.filePathStem === "/index.src",
    canonical: (data) => data.page.filePathStem === "/index.src"
      ? "https://steer.seanfloyd.dev/"
      : `https://steer.seanfloyd.dev${data.page.filePathStem}.html`,
  });

  /* Footer defaults. A page overrides only what differs from every other page. */
  eleventyConfig.addGlobalData("footBottom", true);
  eleventyConfig.addGlobalData("footLegal",
    "macOS 14+ · Apple Silicon · Not affiliated with Sony, Microsoft, or Nintendo.");

  eleventyConfig.addTransform("minify-html", /** @this {{page?: {outputPath?: string}}} */ async function (content) {
    if (!this.page?.outputPath?.endsWith(".html")) return content;
    return minify(content, MINIFY);
  });

  /* The layout links <page>.css only for a page that has one, so a page with no
     sheet requests nothing. Read once at config time, like the band glob. */
  eleventyConfig.addGlobalData("pageSheets", pageSheets());

  eleventyConfig.on("eleventy.before", writeHomeEntry);
  eleventyConfig.on("eleventy.after", () => {
    mkdirSync(OUT, { recursive: true });
    bundle("site.entry.css", "dist/site.css");
    bundle("home.entry.css", "dist/home.css");
    for (const p of pageSheets()) bundle(`pages/${p}.css`, `dist/${p}.css`);
    compileBrowserTs();
    minifyJs();
  });

  return {
    dir: {
      /* src/, not ".": with the repo root as input every file in it was a
         potential page, so .eleventyignore had to name the prose and
         addPassthroughCopy had to name the assets. Both were lists nobody
         updates. Eleventy requires includes and data to sit inside input. */
      input: "src",
      output: "dist",
      /* src/_includes/{bands,chrome,layouts}, mirrored by styles/{bands}. A
         band's two files are at the same path in each tree: swap
         src/_includes -> styles and .html -> .css and you have the sheet. */
      includes: "_includes",
      layouts: "_includes",
      data: "_data",
    },
    htmlTemplateEngine: "njk",
    markdownTemplateEngine: "njk",
  };
}
